# Generated by Django 5.2.8 on 2026-02-24 16:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Grille',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom du Pack')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Prix (FCFA)')),
                ('pourcentage_gain', models.FloatField(verbose_name='% Gain Journalier')),
            ],
            options={
                'verbose_name': 'Catalogue Pack',
                'verbose_name_plural': 'Catalogue Packs',
            },
        ),
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Numéro de téléphone')),
                ('solde', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Solde du compte')),
                ('pack_nom', models.CharField(blank=True, max_length=100, null=True, verbose_name='Pack Actuel')),
                ('pack_montant', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Montant Investi')),
                ('pourcentage_journalier', models.FloatField(default=0.0, verbose_name='% Journalier')),
                ('derniere_maj_gain', models.DateField(blank=True, null=True, verbose_name='Date du dernier gain versé')),
                ('commission_payee', models.BooleanField(default=False, verbose_name='Commission de parrainage versée ?')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name="Date d'inscription")),
                ('parrain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filleuls', to=settings.AUTH_USER_MODEL, verbose_name='Parrain')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil',
                'verbose_name_plural': 'Profils',
            },
        ),
        migrations.CreateModel(
            name='Investissement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_activation', models.DateTimeField(auto_now_add=True)),
                ('actif', models.BooleanField(default=True)),
                ('pack', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.grille')),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investissements', to='users.profil')),
            ],
            options={
                'verbose_name': 'Investissement Actif',
                'verbose_name_plural': 'Investissements Actifs',
            },
        ),
        migrations.CreateModel(
            name='HistoriqueGain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date_distribution', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(default='Gain journalier', max_length=255)),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique_gains', to='users.profil')),
            ],
            options={
                'verbose_name': 'Historique des Gains',
                'verbose_name_plural': 'Historique des Gains',
            },
        ),
    ]
