# Generated by Django 5.2.8 on 2026-01-04 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profil',
            options={'verbose_name': 'Profil', 'verbose_name_plural': 'Profils'},
        ),
        migrations.AlterField(
            model_name='profil',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, verbose_name="Date d'inscription"),
        ),
        migrations.AlterField(
            model_name='profil',
            name='solde',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Solde du compte'),
        ),
        migrations.AlterField(
            model_name='profil',
            name='telephone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Numéro de téléphone'),
        ),
    ]
