# Generated by Django 5.2.8 on 2026-01-11 01:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profil_options_alter_profil_date_creation_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Grille',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom du Pack')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Prix (FCFA)')),
                ('pourcentage_gain', models.FloatField(verbose_name='% Gain Journalier')),
            ],
            options={
                'verbose_name': 'Catalogue Pack',
                'verbose_name_plural': 'Catalogue Packs',
            },
        ),
        migrations.AddField(
            model_name='profil',
            name='commission_payee',
            field=models.BooleanField(default=False, verbose_name='Commission de parrainage versée ?'),
        ),
        migrations.AddField(
            model_name='profil',
            name='derniere_maj_gain',
            field=models.DateField(blank=True, null=True, verbose_name='Date du dernier gain versé'),
        ),
        migrations.AddField(
            model_name='profil',
            name='pack_montant',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Montant Investi'),
        ),
        migrations.AddField(
            model_name='profil',
            name='pack_nom',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Pack Actuel'),
        ),
        migrations.AddField(
            model_name='profil',
            name='parrain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filleuls', to=settings.AUTH_USER_MODEL, verbose_name='Parrain'),
        ),
        migrations.AddField(
            model_name='profil',
            name='pourcentage_journalier',
            field=models.FloatField(default=0.0, verbose_name='% Journalier'),
        ),
        migrations.CreateModel(
            name='HistoriqueGain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date_distribution', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(default='Gain journalier', max_length=255)),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique_gains', to='users.profil')),
            ],
            options={
                'verbose_name': 'Historique des Gains',
                'verbose_name_plural': 'Historique des Gains',
            },
        ),
        migrations.CreateModel(
            name='Investissement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_activation', models.DateTimeField(auto_now_add=True)),
                ('actif', models.BooleanField(default=True)),
                ('pack', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.grille')),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investissements', to='users.profil')),
            ],
            options={
                'verbose_name': 'Investissement Actif',
                'verbose_name_plural': 'Investissements Actifs',
            },
        ),
    ]
