# Generated by Django 5.2.8 on 2026-02-24 16:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_site', models.CharField(default='IIBF INVEST', max_length=100)),
                ('pourcentage_parrainage', models.DecimalField(decimal_places=2, default=5.0, help_text='En pourcentage (ex: 5.00 pour 5%)', max_digits=5)),
            ],
            options={
                'verbose_name': 'Configuration Générale',
                'verbose_name_plural': 'Configuration Générale',
            },
        ),
        migrations.CreateModel(
            name='Grille',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('pourcentage_gain', models.DecimalField(decimal_places=2, max_digits=5)),
                ('duree_jours', models.IntegerField(default=30)),
            ],
        ),
        migrations.CreateModel(
            name='HistoriqueGain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date_distribution', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(default='Gain journalier', max_length=255)),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique_gains_ponzi', to='users.profil')),
            ],
        ),
        migrations.CreateModel(
            name='Investissement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_activation', models.DateTimeField(auto_now_add=True)),
                ('actif', models.BooleanField(default=True)),
                ('grille', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ponzi.grille')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Retrait',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('numero_paiement', models.CharField(max_length=25)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('VALIDE', 'Validé'), ('REJETE', 'Rejeté')], default='EN_ATTENTE', max_length=20)),
                ('date_demande', models.DateTimeField(auto_now_add=True)),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retraits_ponzi', to='users.profil')),
            ],
        ),
    ]
