# Generated by Django 5.2.8 on 2026-01-04 01:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Grille',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=10, unique=True, verbose_name='Nom de la Grille')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=15, verbose_name="Montant de l'investissement")),
                ('pourcentage_gain', models.DecimalField(decimal_places=2, default=10.5, max_digits=5, verbose_name='Pourcentage Journalier (%)')),
            ],
            options={
                'verbose_name': "Grille d'Investissement",
                'verbose_name_plural': "Grilles d'Investissement",
            },
        ),
        migrations.CreateModel(
            name='Investissement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_activation', models.DateTimeField(auto_now_add=True, verbose_name="Date d'activation")),
                ('actif', models.BooleanField(default=True, verbose_name='Statut Actif')),
                ('total_cumule', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Total des gains perçus')),
                ('grille', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ponzi.grille')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mes_investissements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Placement Candidat',
                'verbose_name_plural': 'Placements Candidats',
            },
        ),
        migrations.CreateModel(
            name='HistoriqueGain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Montant du gain')),
                ('date_distribution', models.DateTimeField(auto_now_add=True, verbose_name='Heure du versement')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique_gains', to=settings.AUTH_USER_MODEL)),
                ('investissement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ponzi.investissement')),
            ],
            options={
                'verbose_name': 'Historique des Versements',
                'verbose_name_plural': 'Historique des Versements',
                'ordering': ['-date_distribution'],
            },
        ),
    ]
