# Generated by Django 5.2.8 on 2026-01-04 08:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ponzi', '0001_initial'),
        ('users', '0002_alter_profil_options_alter_profil_date_creation_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_site', models.CharField(default='IIBF INVEST', max_length=100)),
                ('pourcentage_parrainage', models.DecimalField(decimal_places=2, default=5.0, help_text='En pourcentage (ex: 5.00 pour 5%)', max_digits=5)),
            ],
            options={
                'verbose_name': 'Configuration Générale',
                'verbose_name_plural': 'Configuration Générale',
            },
        ),
        migrations.AlterModelOptions(
            name='grille',
            options={},
        ),
        migrations.AlterModelOptions(
            name='historiquegain',
            options={},
        ),
        migrations.AlterModelOptions(
            name='investissement',
            options={},
        ),
        migrations.RemoveField(
            model_name='historiquegain',
            name='investissement',
        ),
        migrations.RemoveField(
            model_name='historiquegain',
            name='utilisateur',
        ),
        migrations.RemoveField(
            model_name='investissement',
            name='total_cumule',
        ),
        migrations.AddField(
            model_name='grille',
            name='duree_jours',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='historiquegain',
            name='description',
            field=models.CharField(default='Gain journalier', max_length=255),
        ),
        migrations.AddField(
            model_name='historiquegain',
            name='profil',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.profil'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='grille',
            name='montant',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='grille',
            name='nom',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='grille',
            name='pourcentage_gain',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='historiquegain',
            name='date_distribution',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='historiquegain',
            name='montant',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='investissement',
            name='actif',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='investissement',
            name='date_activation',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='investissement',
            name='grille',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ponzi.grille'),
        ),
        migrations.AlterField(
            model_name='investissement',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Retrait',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('numero_paiement', models.CharField(max_length=25)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('VALIDE', 'Validé'), ('REJETE', 'Rejeté')], default='EN_ATTENTE', max_length=20)),
                ('date_demande', models.DateTimeField(auto_now_add=True)),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retraits', to='users.profil')),
            ],
        ),
    ]
