# Generated by Django 5.2.8 on 2026-01-11 01:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ponzi', '0002_configuration_alter_grille_options_and_more'),
        ('users', '0003_grille_profil_commission_payee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historiquegain',
            name='profil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique_gains_ponzi', to='users.profil'),
        ),
        migrations.AlterField(
            model_name='retrait',
            name='profil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retraits_ponzi', to='users.profil'),
        ),
    ]
